### ISSUE TITLE
[bug] 依赖项缺少 `httpx`

### ISSUE THREAD

**Issue by shoucandanghehe** [KomoriDev/nonebot-plugin-wakatime#1]
https://github.com/KomoriDev/nonebot-plugin-wakatime/blob/803bd84a123debd388639a42588bb0085db28e5a/pyproject.toml#L8-L15

https://github.com/KomoriDev/nonebot-plugin-wakatime/blob/803bd84a123debd388639a42588bb0085db28e5a/nonebot_plugin_wakatime/__init__.py#L7

https://registry.nonebot.dev/plugin/nonebot-plugin-wakatime:nonebot_plugin_wakatime

**Comment by KomoriDev** [comment]
fixed
