### ISSUE TITLE
[Bug] 异常捕获语法错误

### ISSUE THREAD

**Issue by wyf7685** [KomoriDev/nonebot-plugin-wakatime#15]
https://github.com/KomoriDev/nonebot-plugin-wakatime/blob/master/nonebot_plugin_wakatime/__init__.py#L116

    except ConnectTimeout | TimeoutError:

<details><summary>日志截图</summary>

![3306b924926bf990c71a6c970d60c864_720](https://github.com/user-attachments/assets/dc63409d-1637-409d-854e-6e6d227b9c08)
</details>

解决方案

    except (ConnectTimeout, TimeoutError):

**Comment by KomoriDev** [comment]
草
你方便 pr 吗）

**Comment by wyf7685** [comment]
另外，截图里触发的是 ConnectError, 插件似乎没有处理这个异常
