### ISSUE TITLE
未设置时区导致报错

### ISSUE THREAD

**Issue by Agnes4m** [KomoriDev/nonebot-plugin-wakatime#20]
## 环境

python3.10.8
ubuntu22.04
pypi 0.2.6

## 过程

在设置配置文件后，我进行了绑定操作，然后使用`wakatime`指令，发现报错
随后，我对request.py文件内三个函数进行了logger输出，得出get_all_time_since_today，get_user_stats输出均错误，提示时区问题，get_user_info函数正常输出
在ubuntu中我检查时区设置页没有问题，请问这个错误应该如何解决？
![image](https://github.com/user-attachments/assets/887e30a0-fc12-4290-970c-a523490766e5)
![image](https://github.com/user-attachments/assets/752e6cee-1e28-4c6f-b09b-edc565bfbb76)

**Comment by KomoriDev** [comment]
或许是因为：
![image](https://github.com/user-attachments/assets/d334604b-4c55-416a-a561-15f6f599e7d9)
酱紫试试？
![image](https://github.com/user-attachments/assets/6f18ff8a-80f1-48ce-87f4-32c3e1c217cd)

**Comment by Agnes4m** [comment]
有正常输出了，但是信息有点怪啊
![f7082faee4f113a2d2e1704f8f8155e2_720](https://github.com/user-attachments/assets/f3bedd64-d8e8-43ae-8802-a28949ce4fd2)

**Comment by KomoriDev** [comment]
> 有正常输出了，但是信息有点怪啊
> ![f7082faee4f113a2d2e1704f8f8155e2_720](https://github.com/user-attachments/assets/f3bedd64-d8e8-43ae-8802-a28949ce4fd2)
> 

除了『今日编码时间』以外均显示的上一周的信息，隔段时间就~~应该~~没问题了

`@None` 是因为你 wakatime 没有设置用户名
