### ISSUE TITLE
[提问]redirect_uri是什么参数

### ISSUE THREAD

**Issue by Agnes4m** [KomoriDev/nonebot-plugin-wakatime#5]
redirect_uris是什么参数，应该怎么添加麻烦问问
![image](https://github.com/user-attachments/assets/89e7ca94-7ef1-4115-85fc-c104a47d40d6)

**Comment by KomoriDev** [comment]
redirect uri 填 `https://wakatime.com/oauth/test`，然后配置插件也同样使用这个

**Comment by KomoriDev** [comment]
示例：
![image](https://github.com/user-attachments/assets/4ce7df3e-b8ba-4583-85b5-ff050a1c6a09)
![image](https://github.com/user-attachments/assets/5f0d19d6-0a62-4038-9d1c-b5b7d4cb2654)

**Comment by Agnes4m** [comment]
![image](https://github.com/user-attachments/assets/0aafe6eb-820d-4b6f-b753-8c0b095f2e41)
显示绑定失败

**Comment by KomoriDev** [comment]
检查你的配置有没有填对？
> [400 - Bad Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400): The request is invalid. Check error message and try again.

**Comment by Agnes4m** [comment]
![image](https://github.com/user-attachments/assets/7d57f8cb-4f9d-4066-9404-02023d9e7146)
我qu'er确认和填写的一致

**Comment by KomoriDev** [comment]
LOG_LEVEL 设置成 DEBUG，并重启终端，看看截图

**Comment by Agnes4m** [comment]
![image](https://github.com/user-attachments/assets/bf623246-ddc6-4b9b-aee2-5ca237ae8a2f)

**Comment by KomoriDev** [comment]
https://github.com/KomoriDev/nonebot-plugin-wakatime/blob/803bd84a123debd388639a42588bb0085db28e5a/nonebot_plugin_wakatime/__init__.py#L153

你在这里浅改一下吧（

```diff
- logger.error(f"用户 {user_session.user_id} 绑定失败。状态码：{resp.status_code}") 
+ logger.error(f"用户 {user_session.user_id} 绑定失败。状态码：{resp.status_code}。内容：{resp.content}") 
```

~~不然实在看不出来怎么个事~~

**Comment by Agnes4m** [comment]
内容：b'error=invalid_request&error_description=redirect_uri+does+not+match+the+one+used+for+this+code.'

**Comment by KomoriDev** [comment]
你的 `redirect_uri` 真的配置对了吗？还是说没保存（？

**Comment by Agnes4m** [comment]
确认没问题啊，还是说那个name要和你示例给的一致
![image](https://github.com/user-attachments/assets/36d1cc65-edd4-47f0-ba16-7d2bcea7220a)
![image](https://github.com/user-attachments/assets/d6d1a787-e52c-494c-8a94-4c5bf07da411)

**Comment by Agnes4m** [comment]
所以咋回事捏

**Comment by KomoriDev** [comment]
更新后再试试喵

**Comment by Agnes4m** [comment]
![image](https://github.com/user-attachments/assets/001c0e53-dc46-446f-adf8-3647b8046c16)

**Comment by KomoriDev** [comment]
> ![image](https://private-user-images.githubusercontent.com/70925546/356480359-001c0e53-dc46-446f-adf8-3647b8046c16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODQzMjQsIm5iZiI6MTcyMzE4NDAyNCwicGF0aCI6Ii83MDkyNTU0Ni8zNTY0ODAzNTktMDAxYzBlNTMtZGM0Ni00NDZmLWFkZjgtMzY0N2I4MDQ2YzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDA2MTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MzI2YzE5MjNjN2YxN2NjZGRjNTE3YmMxMGQyNDc1ZGNkMmViOThiMmU2NzVlZWVjZDhkYjMyNDM5OGJjMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SSDfz2YdspQLKjeL6ZnN2qTkwj0Ns0CZq9fBb0wTSiU)

你的 pydantic 版本是？

**Comment by Agnes4m** [comment]
1.10.13

**Comment by KomoriDev** [comment]
> 1.10.13

该插件不兼容 pyd 1 喔（

**Comment by Agnes4m** [comment]
那应该在这里指定pydantic 的版本限制，现在nb2不是已经可以兼容v1和v2了吗？
![image](https://github.com/user-attachments/assets/080e1577-baaa-46e4-a2d3-286629e922e0)

**Comment by KomoriDev** [comment]
插件里面用了 pydantic v2 特性（

**Comment by Agnes4m** [comment]
可以使用custom_validation()解决v1和v2的兼容性问题
![image](https://github.com/user-attachments/assets/51fe37e5-f6d8-4eb1-a496-7bf69792ec93)

**Comment by KomoriDev** [comment]
https://github.com/KomoriDev/nonebot-plugin-wakatime/blob/a8952a0304a08b4164c202c902f6d6f59fb8ca5c/nonebot_plugin_wakatime/config.py#L6

**Comment by KomoriDev** [comment]
已在 #12 兼容 Pydantic v1
